/** Builders for recipe request bodies used across tests. */
export const fullRecipe = (overrides: Record<string, unknown> = {}) => ({
  title: 'Голубцы',
  servings: 4,
  difficulty: 'medium',
  prep_min: 30,
  cook_min: 90,
  language: 'ru',
  author_notes: 'Лучше на следующий день',
  tags: ['main', 'Бабушкины'],
  ingredients: [
    {
      ref: 'farsh',
      name: 'говяжий фарш',
      qty_kind: 'exact',
      amount_min: 800,
      unit_code: 'g',
      unit_raw: 'г',
    },
    {
      ref: 'eggs',
      name: 'яйца',
      qty_kind: 'exact',
      amount_min: 4,
      unit_code: 'pcs',
      unit_raw: 'шт.',
    },
    {
      ref: 'flour',
      name: 'мука',
      qty_kind: 'exact',
      amount_min: 2,
      unit_code: 'cup',
      unit_raw: 'стакана',
      group_label: 'Для соуса',
    },
    {
      ref: 'cream',
      name: 'сметана',
      qty_kind: 'range',
      amount_min: 2,
      amount_max: 3,
      unit_code: 'tbsp',
    },
    { ref: 'bay', name: 'лавровый лист', qty_kind: 'exact', amount_min: 2, unit_code: 'pcs' },
    { ref: 'salt', name: 'соль', qty_kind: 'to_taste', raw_line: 'соль по вкусу' },
  ],
  videos: [{ ref: 'v1', youtube_id: 'dQw4w9WgXcQ', title: 'Как сворачивать' }],
  steps: [
    {
      title: 'Фарш',
      body: 'Смешайте {ing:farsh} и {ing:eggs}.',
      ingredients: [{ ref: 'farsh' }, { ref: 'eggs', portion_fraction: 0.5 }],
    },
    {
      body: 'Тушите 90 минут.',
      video_ref: 'v1',
      video_start_sec: 42,
      ingredients: [{ ref: 'eggs', portion_fraction: 0.5 }, { ref: 'bay' }],
      timers: [{ label: 'Тушение', duration_sec: 5400 }],
    },
  ],
  ...overrides,
});
